---
title: "Data Cleaning"
author: "Joe Barrett"
date: "2022-07-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Churn Analysis

# Reading Data

```{r}
# Cloud Orders
library(readr)
cloud_orders <- read.csv("Data/cloud_orders.csv")
cloud_orders <- subset(cloud_orders, select = -c(EXTENSION,
                                                 ENROLLMENT_DATE,
                                                 NS_INTERNAL_ID,
                                                 PAYING_CUSTOMER_DATE,
                                                 PAYING_CUSTOMER_DATE,
                                                 PRODUCTION_STAGE,
                                                 MENTORSHIP_MILESTONES,
                                                 PAYING_CUSTOMER,
                                                 MENTORSHIP_MILESTONES
                                                 ))
#head(cloud_orders)

# Daily_consumption
daily_consumption <- read.csv("DATA/daily_consumption.csv")
daily_consumption <- subset(daily_consumption, select = -c(CONSUMPTION_DATE))

head(daily_consumption)
# mc_data_v
mc_data_v <- read.csv("Data/mc_data_v.csv")
mc_data_v <- subset(mc_data_v, select = -c(USAGE_COMPLETION_DATE,
                                           CASE_STUDY,
                                           CASE_STUDY_LAST_UPDATE_DATE,
                                           REF_ARCH_COMMENTS,
                                           REF_ARCH_LAST_UPDATE_DATE,
                                           IS_DATE,
                                           ELEVATOR_PITCH_LAST_UPDATE_DATE,
                                           VECTOR_LOGO_LAST_UPDATE_DATE,
                                           MAIL_SENT_DATE,
                                           LAST_UPDATE_DATE,
                                           PROFILE_CREATION_DATE,
                                           ELEVATOR_PITCH,
                                           MAIL_SENT,
                                           LOGO_FILE_COUNT,
                                           NS_INTERNAL_ID,
                                           REF_ARCH_FILE_COUNT,
                                           REF_ARCH_WORKLOAD,
                                           REF_ARCH,
                                           IS_SOLUTION_FLAG,
                                           IS_SOLUTION,
                                           IS_INTEGRATION_FLAG,
                                           VECTOR_LOGO
                                           ))
#head(mc_data_v)

# monthly_usage
monthly_usage <- read.csv("Data/monthly_usage.csv")
monthly_usage <- subset(monthly_usage, select = -c(ORDER_ID
                                                   ))

#head(monthly_usage)

# startup_deetails
# startup_details <- read.csv("Data/startup_details.csv")
# startup_details <- subset(startup_details, select = -c(REGION_CODE,
#                                                        COUNTRY,
#                                                        DIGITAL_CATALOUGE,
#                                                        MENTOR_BENEFIT,
#                                                        MIGRATION_BENEFIT,
#                                                        FUNDRAISING_ACTIVE_FLAG,
#                                                        STAGE))



```
# Merging Data

```{r}
library(dplyr)

df <- cloud_orders %>% right_join(daily_consumption)

df2 <- df %>% right_join(mc_data_v)

df3 <- df2 %>% right_join(startup_details)
# monthly usage is an agregartion of daily usage

#df4 <- df3 %>% right_join(startup_details)

all_data <- df3
########################################################
#                     QUESTIOINS                       #       
#                                                      #
# MAIL_SENT IS MISSIING DATA                           #
# DOES LACK OF Y IN DIGITAL_CATALOG IMPLY A N          #
# DOES LACK OF Y IN MENTOR_BENEFIT IMPLY A N           #
# DOES LACK OF Y IN MIGRATION_BENEFIT IMPLY A N        #
# DOES LACK OF Y IN FUNDRAIISING_ACTIVE_FLAG IMPLY A N #
# What do we do for missing categorical data-TECHNOLOGY#                                #                                                      #
#                                                      #
#                    To - Do                           #
#                            #
########################################################

head(all_data)
colnames(all_data)

unique(all_data$TECHNOLOGY1)

```





```{r cars}
summary(all_data)
```

## Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
library(ggplot2)

all_data <- na.omit(all_data)
med <- median(all_data$CLOUD_USAGE)
med
ggplot(data = all_data, aes(x=INDUSTRY2, y=CLOUD_USAGE)) +
  geom_bar(stat = "identity", aes(fill = COUNTRY)) + 
  labs (x = "Tech Sector",
        y = "Cloud Usage",
        title = "Cloud Usage by Tech Sector")+
  geom_hline(yintercept = med, aes(color = Red))+
  theme(plot.title=element_text(hjust=0.5), axis.text.x = element_text(angle = 45, hjust = 1))
```

## Plotly

```{r}
library(plotly)

plotly_data <- subset(all_data, select = c(INDUSTRY2, CLOUD_USAGE, COUNTRY))

ggplotly(ggplot() + 
           geom_point(data = plotly_data, aes(x = INDUSTRY2, y = CLOUD_USAGE, color = COUNTRY)) + 
           labs(x = 'Tech Sector', 
                y = 'Cloud Usage', 
                title = 'Usage by Tech Sector')+
           geom_smooth(data = plotly_data, aes(x = INDUSTRY2, y = CLOUD_USAGE, color = COUNTRY), se = FALSE, method = "loess") +
           theme(plot.title=element_text(hjust=0.5), axis.text.x = element_text(angle = 45)))

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
